[font]
normal = { family = "Hack Nerd Font", style = "Mono" }
size = 12

[window]
opacity = 1
blur = true

[general]
import = [
    "~/.config/alacritty/themes/one_dark.toml",
]

[colors]
cursor = { text = "CellBackground", cursor = "#cccccc" }
vi_mode_cursor = { text = "CellBackground", cursor = "#cccccc" }
