#!/usr/bin/env bash

set -e

dry="--dry-run"
[[ "$1" == "--real" ]] && dry=""

for i in "$HOME/dotfiles/"*/; do
    dirname=$(basename "$i")
    if [[ -d "$HOME/.config/$dirname" ]]; then
        rsync -av $dry --progress --delete "$HOME/.config/$dirname/" "$i"
    fi
done

sed -i 's/client_id = ".*"/client_id = "" # go to https:\/\/developer.spotify.com\/dashboard/' \
    "$HOME/dotfiles/spotify-player/app.toml"

pacman -Qqe > "$HOME/dotfiles/pkglist.txt"
paru -Qqm > "$HOME/dotfiles/aurpkg.txt"

rsync -av $dry --progress "$HOME/.bashrc" "$HOME/dotfiles/.bashrc"
rsync -av $dry --progress "$HOME/.zshrc" "$HOME/dotfiles/.zshrc"

rsync -av $dry --progress \
  --exclude-from="$HOME/dotfiles/.gitignore" \
  "$HOME/.local/bin/" "$HOME/dotfiles/scripts/"
