#!/usr/bin/env sh
echo "🔋 Switching to Power Saving Mode..."
echo powersave | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor > /dev/null
echo power | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/energy_performance_preference > /dev/null
sudo tlp bat
echo "💚 Maximum power saving activated!"
