#!/usr/bin/env bash
echo "🚀 Switching to Performance Mode..."
echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor > /dev/null
echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/energy_performance_preference > /dev/null
echo "⚡ Performance mode activated!"
