#!/usr/bin/env bash

WALLPAPER_DIR="$HOME/wallpapers/"
WALLPAPER=$(find "$WALLPAPER_DIR" -type f | shuf -n 1)

cat >  ~/.config/hypr/hyprpaper.conf << EOF
preload = $WALLPAPER
wallpaper = ,$WALLPAPER
ipc = true
EOF

hyprpaper
