#!/usr/bin/env sh

case "$1" in
    "--start") 
        sudo systemctl start systemd-resolved
        wg-quick up wgnet0
    ;;
    "--status") sudo wg ;;
    "--stop")
        sudo systemctl stop systemd-resolved
        wg-quick down wgnet0
    ;;
    *) echo "WTF?" ;;
esac
